name: Tests / Code Coverage
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-tests
  cancel-in-progress: true

jobs:
  test-system:
#    needs: [tests, test-integration, test-e2e]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum
            **/go.mod
            **/go.sum
            **/Makefile
            Makefile
      - name: system tests v1
        if: env.GIT_DIFF
        run: |
          COSMOS_BUILD_OPTIONS=legacy make test-system
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: "testnet-setup"
          path: ./systemtests/testnet/
          retention-days: 3
